import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import "./media.css"
import { Toaster } from 'react-hot-toast';
import { LanguageProvider } from "./context/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['100', '300', '400', '500', '700', '900']
})

export const metadata = {
  title: "XALQARO TA'LIM, ILMIY-AMALIY TADQIQOT MARKAZI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="/xalq.png"></link>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto} antialiased`}
      >
        <Toaster position="top-right" reverseOrder={false} />
        <LanguageProvider>{children}</LanguageProvider>

      </body>
    </html>
  );
}
